import type { FullBox } from "./proofbox-queries";
import { displayStatus, dueLabel, formatDate, formatDateTime, formatMoney } from "./proofbox-data";

const GREEN: [number, number, number] = [16, 122, 87];
const INK: [number, number, number] = [24, 32, 30];
const MUTED: [number, number, number] = [110, 118, 114];
const LINE: [number, number, number] = [222, 228, 225];

export async function downloadCertificate(box: FullBox) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 56;
  const contentW = pageW - margin * 2;
  let y = 0;

  const status = displayStatus(box.status, box.due_date);

  // Header band
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, pageW, 96, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("ProofBox Certificate", margin, 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Reference ${box.code}  ·  ${status}`, margin, 66);
  y = 128;

  const heading = (text: string) => {
    if (y > 740) { doc.addPage(); y = 64; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...GREEN);
    doc.text(text.toUpperCase(), margin, y);
    y += 8;
    doc.setDrawColor(...LINE);
    doc.line(margin, y, margin + contentW, y);
    y += 20;
  };

  const row = (label: string, value: string) => {
    if (y > 760) { doc.addPage(); y = 64; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...MUTED);
    doc.text(label, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...INK);
    const lines = doc.splitTextToSize(value || "—", contentW - 150) as string[];
    doc.text(lines, margin + 150, y);
    y += Math.max(lines.length * 13, 16) + 4;
  };

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.setTextColor(...INK);
  const titleLines = doc.splitTextToSize(box.title, contentW) as string[];
  doc.text(titleLines, margin, y);
  y += titleLines.length * 22 + 12;

  heading("Agreement details");
  row("Type", box.type);
  row("Description", box.description ?? "—");
  row("Value", box.amount !== null ? formatMoney(box.amount, box.currency) : "No amount recorded");
  row("Start date", formatDate(box.start_date));
  row("Due date", dueLabel(box.status, box.due_date, box.completed_at));
  row("Terms", box.terms ?? "—");
  row("Created", formatDateTime(box.created_at));
  if (box.completed_at) row("Completed", formatDateTime(box.completed_at));
  y += 8;

  heading("Participants");
  for (const p of box.participants ?? []) {
    const name = p.display_name ?? p.invite_email ?? "Participant";
    const state = p.confirmation_status === "confirmed"
      ? `Confirmed${p.confirmed_at ? ` on ${formatDate(p.confirmed_at)}` : ""}`
      : p.confirmation_status === "changes_requested" ? "Requested changes" : "Pending";
    row(name, `${p.role} · ${state}`);
  }
  y += 8;

  const events = [...(box.timeline_events ?? [])].sort(
    (a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime(),
  );
  if (events.length > 0) {
    heading("History");
    for (const event of events) {
      row(formatDateTime(event.created_at), event.description ?? event.event_type);
    }
    y += 8;
  }

  // Footer
  if (y > 720) { doc.addPage(); y = 64; }
  doc.setDrawColor(...LINE);
  doc.line(margin, y, margin + contentW, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(
    `Verify this record at any time with reference code ${box.code}. Generated by ProofBox on ${formatDateTime(new Date().toISOString())}.`,
    margin,
    y,
    { maxWidth: contentW },
  );

  doc.save(`proofbox-${box.code.toLowerCase()}-certificate.pdf`);
}
