import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Camera, Check, CheckCircle2, Clock3, Eye, FileCheck2, History, Image, LockKeyhole, PackageCheck, ShieldCheck, UserCheck, UsersRound } from "lucide-react";
import { ProofBoxLogo } from "@/components/proofbox-logo";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/proofbox-ui";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "ProofBox — Make agreements clear" }, { name: "description", content: "Record agreements, attach evidence, confirm with everyone involved and keep a clear history." }, { property: "og:title", content: "ProofBox — Make agreements clear" }, { property: "og:description", content: "Record agreements, attach evidence and keep a clear shared history." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Index,
});

function Index() {
  return <div className="min-h-screen bg-background"><header className="sticky top-0 z-30 border-b bg-background/90 backdrop-blur"><div className="mx-auto grid h-16 max-w-7xl grid-cols-[minmax(0,1fr)_auto] items-center px-4 sm:px-6 lg:px-8"><Link to="/" aria-label="ProofBox home"><ProofBoxLogo /></Link><nav className="hidden items-center gap-7 md:flex" aria-label="Website navigation"><a href="#how" className="text-sm font-medium text-muted-foreground hover:text-foreground">How it works</a><a href="#uses" className="text-sm font-medium text-muted-foreground hover:text-foreground">Use cases</a><a href="#privacy" className="text-sm font-medium text-muted-foreground hover:text-foreground">Privacy</a><a href="/verify" className="text-sm font-medium text-muted-foreground hover:text-foreground">Verify a record</a><Button asChild size="sm"><Link to="/auth" search={{ invite: "" }}>Sign in</Link></Button></nav><Button asChild size="sm" className="md:hidden"><Link to="/auth" search={{ invite: "" }}>Sign in</Link></Button></div></header>
  <main><section className="overflow-hidden border-b"><div className="mx-auto grid min-h-[calc(100svh-4rem)] max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 md:min-h-[720px] lg:grid-cols-[0.9fr_1.1fr] lg:px-8 lg:py-20"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border bg-card px-3 py-1.5 text-xs font-semibold text-muted-foreground"><ShieldCheck className="size-3.5 text-primary" />A shared record everyone can trust</div><h1 className="max-w-2xl text-4xl font-bold leading-[1.08] sm:text-5xl lg:text-6xl">Make agreements clear. <span className="text-primary">Keep the proof.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground sm:text-lg sm:leading-8">Record what was agreed, attach evidence, confirm with the people involved, and keep a history that stays clear over time.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><Link to="/auth" search={{ invite: "" }}>Create a ProofBox<ArrowRight /></Link></Button><Button asChild variant="outline" size="lg"><a href="#how">See how it works</a></Button></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted-foreground"><span className="inline-flex items-center gap-1.5"><Check className="size-4 text-success" />Shared confirmation</span><span className="inline-flex items-center gap-1.5"><Check className="size-4 text-success" />Evidence in one place</span><span className="inline-flex items-center gap-1.5"><Check className="size-4 text-success" />Clear history</span></div></div><ProductPreview /></div></section>
  <section id="how" className="border-b bg-card py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><Eyebrow>How it works</Eyebrow><h2 className="mt-3 max-w-xl text-3xl font-bold sm:text-4xl">From conversation to a clear shared record.</h2><div className="mt-12 grid gap-8 md:grid-cols-3"><Step n="01" icon={FileCheck2} title="Create" text="Record what happened, who was involved, dates, amounts and responsibilities." /><Step n="02" icon={UserCheck} title="Confirm" text="Invite the other people to review the details and confirm what was agreed." /><Step n="03" icon={History} title="Keep the proof" text="Evidence, confirmations and every future change stay together in one clear history." /></div></div></section>
  <section id="uses" className="border-b py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><Eyebrow>Everyday agreements</Eyebrow><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Clarity for the things people already do.</h2><p className="mt-4 max-w-md leading-7 text-muted-foreground">ProofBox fits real life—from lending an item to completing paid work.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{["Borrowing","Payments","Sales","Rentals","Freelance work","Services","Deliveries","Personal commitments"].map((item) => <div key={item} className="flex min-h-24 items-end rounded-lg border bg-card p-4 text-sm font-semibold shadow-card">{item}</div>)}</div></div></div></section>
  <section className="border-b bg-secondary py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><Eyebrow>Why ProofBox</Eyebrow><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Trust comes from seeing the full picture.</h2><div className="mt-10 grid gap-px overflow-hidden rounded-lg border bg-border md:grid-cols-5">{[[FileCheck2,"Clear agreements"],[UsersRound,"Shared confirmation"],[Image,"Evidence attached"],[History,"History preserved"],[Clock3,"Timely reminders"]].map(([Icon,label]) => { const I = Icon as typeof Check; return <div key={label as string} className="bg-card p-5"><I className="size-5 text-primary" /><p className="mt-5 text-sm font-semibold">{label as string}</p></div>; })}</div></div></section>
  <section id="privacy" className="border-b py-20 sm:py-24"><div className="mx-auto grid max-w-6xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="rounded-lg border bg-card p-6 shadow-card"><div className="flex items-center gap-3 border-b pb-5"><span className="grid size-10 place-items-center rounded-full bg-primary-soft text-primary"><LockKeyhole className="size-5" /></span><div><p className="font-semibold">Who can see Camera Borrow?</p><p className="text-sm text-muted-foreground">Only people you invite</p></div></div><div className="space-y-3 pt-5"><Person initials="MI" name="You" access="Owner · Full access" /><Person initials="AB" name="Ahmed Bello" access="Participant · Can review and confirm" /></div><div className="mt-5 rounded-md bg-secondary p-3 text-sm text-muted-foreground"><Eye className="mr-2 inline size-4 text-primary" />This ProofBox is not public or searchable.</div></div><div><Eyebrow>Privacy by design</Eyebrow><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Your record. Your people. Your control.</h2><p className="mt-5 max-w-lg leading-7 text-muted-foreground">You decide who can see each ProofBox. Invite only the people involved and keep sensitive evidence private.</p></div></div></section>
  <section className="bg-primary py-20 text-primary-foreground"><div className="mx-auto max-w-3xl px-4 text-center sm:px-6"><h2 className="text-3xl font-bold sm:text-4xl">Make the next agreement clear.</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-primary-foreground/80">Put the details, evidence and confirmation in one place from the start.</p><Button asChild variant="secondary" size="lg" className="mt-7"><Link to="/auth" search={{ invite: "" }}>Create a ProofBox<ArrowRight /></Link></Button></div></section></main>
  <footer className="border-t bg-card"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><ProofBoxLogo /><p className="text-sm text-muted-foreground">Make agreements clear. Keep the proof.</p><p className="text-xs text-muted-foreground">© 2026 ProofBox</p></div></footer></div>;
}

function ProductPreview() { return <div className="relative mx-auto w-full max-w-xl lg:mr-0"><div className="absolute -inset-4 rounded-xl bg-primary-soft" /><div className="relative overflow-hidden rounded-lg border bg-card shadow-card-hover"><div className="flex items-center justify-between border-b px-5 py-4"><ProofBoxLogo /><span className="text-xs font-medium text-muted-foreground">PB-260907-041</span></div><div className="p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-md bg-secondary text-primary"><Camera className="size-5" /></span><div className="min-w-0"><p className="truncate text-lg font-bold">Camera Borrow</p><p className="text-sm text-muted-foreground">₦500,000 estimated value</p></div></div><StatusBadge status="Awaiting confirmation" className="hidden sm:flex" /></div><div className="mt-6 rounded-md border"><PreviewRow label="Owner" value="Muhammed Imam" /><PreviewRow label="Borrower" value="Ahmed Bello" /><PreviewRow label="Return date" value="September 15, 2026" /><PreviewRow label="Evidence" value="4 files attached" /></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-md bg-success-soft p-3"><CheckCircle2 className="size-4 text-success" /><p className="mt-2 text-sm font-semibold">Muhammed</p><p className="text-xs text-muted-foreground">Confirmed</p></div><div className="rounded-md bg-warning-soft p-3"><Clock3 className="size-4 text-warning-foreground" /><p className="mt-2 text-sm font-semibold">Ahmed</p><p className="text-xs text-muted-foreground">Waiting</p></div></div><div className="mt-5 flex items-center gap-2 text-xs font-medium text-muted-foreground"><ShieldCheck className="size-4 text-primary" />Confirmed details stay preserved.</div></div></div></div>; }
function PreviewRow({ label, value }: { label: string; value: string }) { return <div className="grid grid-cols-[100px_minmax(0,1fr)] gap-3 border-b px-4 py-3 text-sm last:border-0"><span className="text-muted-foreground">{label}</span><span className="truncate font-medium">{value}</span></div>; }
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="text-xs font-bold uppercase text-primary">{children}</p>; }
function Step({ n, icon: Icon, title, text }: { n: string; icon: typeof Check; title: string; text: string }) { return <div className="border-t-2 border-primary pt-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-md bg-primary-soft text-primary"><Icon className="size-5" /></span><span className="text-sm font-bold text-muted-foreground">{n}</span></div><h3 className="mt-6 text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
function Person({ initials, name, access }: { initials: string; name: string; access: string }) { return <div className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-secondary text-xs font-bold">{initials}</span><div className="min-w-0"><p className="truncate text-sm font-semibold">{name}</p><p className="truncate text-xs text-muted-foreground">{access}</p></div><CheckCircle2 className="size-4 text-success" /></div>; }
