import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { CreateTypeCard, typeChoices } from "@/components/proofbox-ui";

export const Route = createFileRoute("/proofboxes/create")({ head: () => ({ meta: [{ title: "Create a ProofBox" }, { name: "description", content: "Record a clear agreement and invite the people involved." }, { property: "og:title", content: "Create a ProofBox" }, { property: "og:description", content: "Record a clear agreement and invite the people involved." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: CreatePage });
function CreatePage() { const [selected, setSelected] = useState("Borrow"); return <AppShell><div className="mx-auto max-w-4xl"><Link to="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Back</Link><h1 className="text-2xl font-bold sm:text-3xl">What are you recording?</h1><p className="mt-2 text-muted-foreground">Choose the closest match. You can adjust every detail before sharing.</p>
  <div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{typeChoices.map((choice) => <CreateTypeCard key={choice.label} {...choice} selected={selected === choice.label} onClick={() => setSelected(choice.label)} />)}</div>
  <Tabs defaultValue="describe" className="mt-9"><TabsList className="grid w-full max-w-sm grid-cols-2"><TabsTrigger value="describe">Describe it</TabsTrigger><TabsTrigger value="manual">Manual form</TabsTrigger></TabsList><TabsContent value="describe" className="mt-5"><div className="rounded-lg border bg-card p-4 shadow-card sm:p-6"><Label htmlFor="description" className="text-base font-semibold">Or describe what happened</Label><p className="mt-1 text-sm text-muted-foreground">Use your own words. Nothing is submitted until you review it.</p><Textarea id="description" className="mt-4 min-h-40 resize-none text-base leading-7" placeholder="“I lent Ahmed my camera worth ₦500,000 today. He will return it on Friday and cover any damage.”" /><div className="mt-4 flex justify-end"><Button onClick={() => toast("Demo only", { description: "Automatic drafting will be connected in a later phase." })}><Sparkles />Create ProofBox</Button></div></div></TabsContent>
  <TabsContent value="manual" className="mt-5"><div className="rounded-lg border bg-card p-4 shadow-card sm:p-6"><div className="grid gap-5 sm:grid-cols-2"><Field id="title" label="Record title" placeholder="Camera Borrow" /><Field id="participant" label="Other participant" placeholder="Ahmed Bello" /><Field id="amount" label="Amount or item value" placeholder="₦500,000" /><Field id="due" label="Due or return date" placeholder="15 September 2026" /><div className="sm:col-span-2"><Label htmlFor="terms">What was agreed?</Label><Textarea id="terms" className="mt-2 min-h-28" placeholder="Describe responsibilities, conditions and anything else that should be clear." /></div></div><div className="mt-5 flex justify-end"><Button onClick={() => toast.success("Draft prepared", { description: "This preview uses mock data and has not been saved." })}>Review draft<ArrowRight /></Button></div></div></TabsContent></Tabs></div></AppShell>; }
function Field({ id, label, placeholder }: { id: string; label: string; placeholder: string }) { return <div><Label htmlFor={id}>{label}</Label><Input id={id} placeholder={placeholder} className="mt-2 h-11" /></div>; }