import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Check, FilePenLine, Flag, MoreHorizontal, Share2, Upload } from "lucide-react";
import { toast } from "sonner";
import { AppShell, SectionHeading } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { AgreementRows, ConfirmationPanel, EvidenceCard, ParticipantCard, StatusBadge, Timeline } from "@/components/proofbox-ui";
import { timelineEvents } from "@/lib/proofbox-data";

export const Route = createFileRoute("/proofboxes/$id/")({ head: () => ({ meta: [{ title: "Camera Borrow — ProofBox" }, { name: "description", content: "Review the Camera Borrow agreement, evidence and confirmation history." }, { property: "og:title", content: "Camera Borrow — ProofBox" }, { property: "og:description", content: "Review the Camera Borrow agreement, evidence and confirmation history." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: DetailsPage });
function DetailsPage() { const demo = (label: string) => toast("Demo action", { description: `${label} will be available when ProofBox is connected.` }); return <AppShell><Link to="/proofboxes" className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />All ProofBoxes</Link><header className="mt-5 grid grid-cols-[minmax(0,1fr)_auto] gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold sm:text-3xl">Camera Borrow</h1><StatusBadge status="Awaiting confirmation" /></div><p className="mt-2 font-medium text-muted-foreground">₦500,000 estimated value · PB-260907-041</p></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="icon" aria-label="More actions"><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => demo("Share")}>Share</DropdownMenuItem><DropdownMenuItem onClick={() => demo("Amend")}>Amend</DropdownMenuItem><DropdownMenuItem onClick={() => demo("Report dispute")} className="text-destructive">Report dispute</DropdownMenuItem></DropdownMenuContent></DropdownMenu></header>
  <div className="mt-8 grid items-start gap-8 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-9"><section><SectionHeading title="Agreement" /><div className="rounded-lg border bg-card px-4 shadow-card sm:px-6"><AgreementRows /></div></section><section><SectionHeading title="Participants" /><div className="grid gap-3"><ParticipantCard name="Muhammed Imam" role="Owner" initials="MI" confirmed time="Sep 7 · 9:24 AM" /><ParticipantCard name="Ahmed Bello" role="Borrower" initials="AB" confirmed={false} /></div></section><section><SectionHeading title="Evidence" action={<Button variant="outline" size="sm" onClick={() => demo("Add evidence")}><Upload />Add</Button>} /><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><EvidenceCard title="Camera front" type="photo" meta="Photo · 2.4 MB" /><EvidenceCard title="Camera body" type="photo" meta="Photo · 2.1 MB" /><EvidenceCard title="Purchase receipt" type="receipt" meta="PDF · 840 KB" /><EvidenceCard title="Chat screenshot" type="screenshot" meta="Image · 1.2 MB" /></div></section><section><SectionHeading title="History" /><div className="rounded-lg border bg-card p-5 sm:p-6"><Timeline events={timelineEvents} /></div></section></div>
  <aside className="space-y-4 lg:sticky lg:top-24"><div className="rounded-lg border bg-card p-5 shadow-card"><h2 className="font-semibold">Next step</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Ahmed needs to review and confirm this record.</p><Button asChild className="mt-4 w-full"><Link to="/proofboxes/$id/confirm" params={{ id: "camera-borrow" }}><Check />Review confirmation</Link></Button><div className="mt-2 grid grid-cols-2 gap-2"><Button variant="outline" onClick={() => demo("Share")}><Share2 />Share</Button><Button variant="outline" onClick={() => demo("Amend")}><FilePenLine />Amend</Button></div><Button variant="ghost" className="mt-2 w-full text-muted-foreground" onClick={() => demo("Mark completed")}>Mark completed</Button><Button variant="ghost" className="w-full text-destructive hover:text-destructive" onClick={() => demo("Report dispute")}><Flag />Report dispute</Button></div><ConfirmationPanel compact /></aside></div></AppShell>; }