import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Check, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AgreementRows, StatusBadge } from "@/components/proofbox-ui";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";

export const Route = createFileRoute("/proofboxes/$id/confirm")({ head: () => ({ meta: [{ title: "Review Camera Borrow — ProofBox" }, { name: "description", content: "Review agreement details before confirming this ProofBox." }, { property: "og:title", content: "Review Camera Borrow — ProofBox" }, { property: "og:description", content: "Review agreement details before confirming this ProofBox." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ConfirmPage });
function ConfirmPage() { const [checked, setChecked] = useState(false); return <AppShell><div className="mx-auto max-w-2xl"><Link to="/proofboxes/$id" params={{ id: "camera-borrow" }} className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Back to record</Link><div className="mt-6 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-primary-soft text-primary"><ShieldCheck className="size-6" /></span><h1 className="mt-4 text-2xl font-bold sm:text-3xl">Review before you confirm</h1><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-muted-foreground">Take a moment to check every detail. Your confirmation becomes part of the preserved record.</p></div><div className="mt-7 rounded-lg border bg-card p-5 shadow-card sm:p-7"><div className="flex items-center justify-between gap-4 border-b pb-5"><div><h2 className="text-lg font-semibold">Camera Borrow</h2><p className="mt-1 text-sm text-muted-foreground">₦500,000 estimated value</p></div><StatusBadge status="Awaiting confirmation" /></div><AgreementRows /><div className="mt-2 flex items-start gap-3 rounded-md bg-secondary p-4"><Checkbox id="confirm-check" checked={checked} onCheckedChange={(value) => setChecked(value === true)} className="mt-0.5" /><label htmlFor="confirm-check" className="cursor-pointer text-sm font-medium leading-6">I have reviewed these details and confirm that they accurately represent what was agreed.</label></div><Button asChild disabled={!checked} className="mt-5 w-full"><Link to="/proofboxes/$id/confirmed" params={{ id: "camera-borrow" }}><Check />Confirm ProofBox</Link></Button><Button variant="ghost" className="mt-2 w-full">Request changes</Button></div></div></AppShell>; }