import { createFileRoute } from "@tanstack/react-router";
import { Bell, Database, Download, LockKeyhole, LogOut, Shield, UserRound } from "lucide-react";
import { toast } from "sonner";
import { AppShell, PageHeading } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";

export const Route = createFileRoute("/settings")({ head: () => ({ meta: [{ title: "Profile & Settings — ProofBox" }, { name: "description", content: "Manage your ProofBox profile, privacy and notifications." }, { property: "og:title", content: "Profile & Settings — ProofBox" }, { property: "og:description", content: "Manage your ProofBox profile, privacy and notifications." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: SettingsPage });
function SettingsPage() { return <AppShell><PageHeading title="Profile & settings" description="Manage your account, privacy and notification preferences." /><div className="mt-7 grid items-start gap-6 lg:grid-cols-[220px_minmax(0,1fr)]"><nav className="hidden space-y-1 lg:block">{[[UserRound,"Profile"],[Bell,"Notifications"],[Shield,"Privacy"],[LockKeyhole,"Security"],[Database,"Data & export"]].map(([Icon,label]) => { const I = Icon as typeof UserRound; return <button key={label as string} className="flex h-10 w-full items-center gap-3 rounded-md px-3 text-left text-sm font-medium text-muted-foreground first:bg-secondary first:text-foreground"><I className="size-4" />{label as string}</button>; })}</nav><div className="space-y-6"><SettingsCard title="Profile information" description="The details shown to people you share records with."><div className="grid gap-5 sm:grid-cols-2"><Field id="name" label="Full name" value="Muhammed Taiwo Imam-Abubakar" /><Field id="email" label="Email" value="muhammed@example.com" /><Field id="phone" label="Phone number" value="+234 801 234 5678" /></div><Button className="mt-5" onClick={() => toast.success("Profile preview updated")}>Save changes</Button></SettingsCard><SettingsCard title="Notification preferences" description="Choose which updates you want to receive."><Toggle label="Confirmation updates" detail="When someone confirms or requests changes" checked /><Toggle label="Due date reminders" detail="Before an agreement or commitment is due" checked /><Toggle label="Evidence updates" detail="When someone attaches new evidence" checked={false} /></SettingsCard><SettingsCard title="Privacy & security" description="You control who can access every record."><Toggle label="Require secure links" detail="Only invited people can open shared ProofBoxes" checked /><Toggle label="Hide profile phone number" detail="Do not show your number on shared records" checked={false} /><Button variant="outline" className="mt-3"><LockKeyhole />Review security</Button></SettingsCard><SettingsCard title="Your data" description="Download a copy of your ProofBox records and evidence."><Button variant="outline" onClick={() => toast("Demo only", { description: "Data export will be available in a later phase." })}><Download />Request data export</Button></SettingsCard><Button variant="ghost" className="text-destructive hover:text-destructive"><LogOut />Log out</Button></div></div></AppShell>; }
function SettingsCard({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="rounded-lg border bg-card p-5 shadow-card sm:p-6"><h2 className="font-semibold">{title}</h2><p className="mt-1 mb-5 text-sm text-muted-foreground">{description}</p>{children}</section>; }
function Field({ id, label, value }: { id: string; label: string; value: string }) { return <div><Label htmlFor={id}>{label}</Label><Input id={id} defaultValue={value} className="mt-2 h-11" /></div>; }
function Toggle({ label, detail, checked }: { label: string; detail: string; checked: boolean }) { return <div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-t py-4 first:border-t-0 first:pt-0"><div><p className="text-sm font-medium">{label}</p><p className="mt-0.5 text-xs text-muted-foreground">{detail}</p></div><Switch defaultChecked={checked} aria-label={label} /></div>; }