import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Activity } from "lucide-react";
import { AppShell, PageHeading } from "@/components/app-shell";
import { ProductEmpty, PageSkeleton } from "@/components/product-states";
import { Timeline } from "@/components/proofbox-ui";
import { fetchActivity } from "@/lib/proofbox-queries";
import { formatDateTime } from "@/lib/proofbox-data";

export const Route = createFileRoute("/_authenticated/activity")({ head: () => ({ meta: [{ title: "Activity — ProofBox" }, { name: "description", content: "Review what happened across all your ProofBox records." }, { property: "og:title", content: "Activity — ProofBox" }, { property: "og:description", content: "Review what happened across all your ProofBox records." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ActivityPage });
function ActivityPage() { const query = useQuery({ queryKey: ["activity"], queryFn: fetchActivity }); const grouped = new Map<string, NonNullable<typeof query.data>>(); for (const event of query.data ?? []) { const date = new Date(event.created_at); const today = new Date(); const yesterday = new Date(); yesterday.setDate(today.getDate() - 1); const key = date.toDateString() === today.toDateString() ? "Today" : date.toDateString() === yesterday.toDateString() ? "Yesterday" : today.getTime() - date.getTime() < 7 * 86_400_000 ? "This week" : "Earlier"; grouped.set(key, [...(grouped.get(key) ?? []), event]); } return <AppShell><PageHeading title="Activity" description="A clear history of what happened across your records." />{query.isLoading ? <PageSkeleton /> : (query.data ?? []).length === 0 ? <div className="mt-7"><ProductEmpty icon={Activity} title="No activity yet" description="Creation, invitations, evidence, confirmations and amendments will appear here." /></div> : <div className="mt-8 space-y-9">{["Today", "Yesterday", "This week", "Earlier"].map((label) => { const events = grouped.get(label); if (!events?.length) return null; return <section key={label}><h2 className="mb-4 text-lg font-semibold">{label}</h2><div className="rounded-lg border bg-card p-5 shadow-card"><Timeline events={events.map((event) => ({ type: event.event_type, title: event.description ?? event.event_type, detail: event.proof_boxes?.title ?? event.actor_name ?? "", time: formatDateTime(event.created_at) }))} />{events[0]?.proof_boxes && <Link to="/proofboxes/$id" params={{ id: events[0].proof_boxes.id }} className="mt-5 inline-block text-sm font-semibold text-primary">Open latest record</Link>}</div></section>; })}</div>}</AppShell>; }