import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { FileText, FolderOpen } from "lucide-react";
import { toast } from "sonner";
import { AppShell, PageHeading } from "@/components/app-shell";
import { EvidenceCard, SearchBar } from "@/components/proofbox-ui";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ProductEmpty, PageSkeleton } from "@/components/product-states";
import { evidenceUrl, fetchEvidenceVault } from "@/lib/proofbox-queries";
import { fileSize, formatDate } from "@/lib/proofbox-data";

export const Route = createFileRoute("/_authenticated/evidence")({ head: () => ({ meta: [{ title: "Evidence — ProofBox" }, { name: "description", content: "Everything attached to your ProofBoxes, in one private place." }, { property: "og:title", content: "Evidence — ProofBox" }, { property: "og:description", content: "Everything attached to your ProofBoxes, in one private place." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: EvidencePage });
function EvidencePage() { const [search, setSearch] = useState(""); const [type, setType] = useState("all"); const query = useQuery({ queryKey: ["evidence-vault"], queryFn: fetchEvidenceVault }); const items = (query.data ?? []).filter((item) => (type === "all" || (type === "images" ? item.file_type?.startsWith("image/") : item.file_type === "application/pdf"))).filter((item) => `${item.file_name} ${item.description ?? ""} ${item.proof_boxes?.title ?? ""}`.toLowerCase().includes(search.toLowerCase())); return <AppShell><PageHeading title="Evidence" description="Everything you've attached to your ProofBoxes, in one place." /><div className="mt-7 flex gap-2"><SearchBar placeholder="Search evidence" value={search} onChange={setSearch} /><Select value={type} onValueChange={setType}><SelectTrigger className="h-11 w-36 bg-card"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All files</SelectItem><SelectItem value="images">Images</SelectItem><SelectItem value="pdfs">PDFs</SelectItem></SelectContent></Select></div>{query.isLoading ? <PageSkeleton /> : items.length === 0 ? <div className="mt-6"><ProductEmpty icon={FolderOpen} title="No evidence" description="Receipts, photos, screenshots and documents attached to your records will appear here." /></div> : <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-4">{items.map((item) => <div key={item.id}><EvidenceCard title={item.file_name} fileType={item.file_type} meta={`${fileSize(item.file_size)} · ${formatDate(item.created_at)}`} onClick={() => void evidenceUrl(item.file_path).then((url) => window.open(url, "_blank", "noopener")).catch((error: Error) => toast.error(error.message))} /><Link to="/proofboxes/$id" params={{ id: item.proof_box_id }} className="mt-2 block truncate text-xs font-medium text-primary">{item.proof_boxes?.title ?? "View ProofBox"}</Link></div>)}</div>}</AppShell>; }