import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BellRing, Check, Plus } from "lucide-react";
import { toast } from "sonner";
import { AppShell, PageHeading } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ProductEmpty, PageSkeleton } from "@/components/product-states";
import { addReminder, fetchBoxes, fetchReminders, toggleReminder } from "@/lib/proofbox-queries";
import { formatDateTime } from "@/lib/proofbox-data";

export const Route = createFileRoute("/_authenticated/reminders")({ head: () => ({ meta: [{ title: "Reminders — ProofBox" }, { name: "description", content: "Create and manage reminders for agreements, payments, returns and confirmations." }, { property: "og:title", content: "Reminders — ProofBox" }, { property: "og:description", content: "Create and manage reminders for important ProofBox events." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: RemindersPage });

function RemindersPage() { const [open, setOpen] = useState(false); const client = useQueryClient(); const query = useQuery({ queryKey: ["reminders"], queryFn: fetchReminders }); const boxes = useQuery({ queryKey: ["boxes"], queryFn: fetchBoxes }); const mutation = useMutation({ mutationFn: addReminder, onSuccess: () => { setOpen(false); toast.success("Reminder created"); void client.invalidateQueries({ queryKey: ["reminders"] }); } }); return <AppShell><PageHeading title="Reminders" description="Keep track of due dates, payments, returns, confirmations and custom events." action={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus />Create reminder</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create reminder</DialogTitle><DialogDescription>Choose when ProofBox should bring this back to your attention.</DialogDescription></DialogHeader><ReminderForm boxes={boxes.data ?? []} busy={mutation.isPending} onSubmit={(values) => mutation.mutate(values)} /></DialogContent></Dialog>} />{query.isLoading ? <PageSkeleton /> : (query.data ?? []).length === 0 ? <div className="mt-7"><ProductEmpty icon={BellRing} title="You're all caught up" description="Create a reminder for a payment, return, confirmation or any important event." action={<Button onClick={() => setOpen(true)}><Plus />Create reminder</Button>} /></div> : <div className="mt-7 space-y-3">{(query.data ?? []).map((item) => <article key={item.id} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 rounded-lg border bg-card p-4 shadow-card"><div className="min-w-0"><div className="flex items-center gap-2"><span className="rounded-md bg-primary-soft px-2 py-1 text-xs font-semibold capitalize text-primary">{item.reminder_type.replace("_", " ")}</span>{item.completed && <span className="text-xs font-medium text-success">Completed</span>}</div><h2 className="mt-2 truncate font-semibold">{item.title}</h2><p className="mt-1 text-sm text-muted-foreground">{formatDateTime(item.remind_at)}{item.advance_days > 0 ? ` · ${item.advance_days} days before` : ""}</p></div><Button size="icon" variant="outline" aria-label={item.completed ? "Reopen reminder" : "Complete reminder"} onClick={() => void toggleReminder(item.id, !item.completed).then(() => query.refetch())}><Check /></Button></article>)}</div>}</AppShell>; }

function ReminderForm({ boxes, busy, onSubmit }: { boxes: Awaited<ReturnType<typeof fetchBoxes>>; busy: boolean; onSubmit: (values: Parameters<typeof addReminder>[0]) => void }) { const [type, setType] = useState("custom"); const [boxId, setBoxId] = useState("none"); const [advance, setAdvance] = useState("0"); return <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); onSubmit({ title: String(data.get("title")), reminder_type: type, remind_at: new Date(String(data.get("remind_at"))).toISOString(), advance_days: Number(advance), proof_box_id: boxId === "none" ? null : boxId, note: String(data.get("note") ?? "") || null }); }}><div><Label htmlFor="reminder-title">Title</Label><Input id="reminder-title" name="title" required className="mt-2 h-11" placeholder="Camera return" /></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Type</Label><Select value={type} onValueChange={setType}><SelectTrigger className="mt-2 h-11"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="due_date">Due date</SelectItem><SelectItem value="payment">Payment</SelectItem><SelectItem value="return">Return</SelectItem><SelectItem value="confirmation">Confirmation</SelectItem><SelectItem value="custom">Custom event</SelectItem></SelectContent></Select></div><div><Label>Remind me</Label><Select value={advance} onValueChange={setAdvance}><SelectTrigger className="mt-2 h-11"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="0">On the day</SelectItem><SelectItem value="1">1 day before</SelectItem><SelectItem value="3">3 days before</SelectItem><SelectItem value="7">1 week before</SelectItem></SelectContent></Select></div></div><div><Label htmlFor="remind-at">Date and time</Label><Input id="remind-at" name="remind_at" type="datetime-local" required className="mt-2 h-11" /></div><div><Label>Related ProofBox</Label><Select value={boxId} onValueChange={setBoxId}><SelectTrigger className="mt-2 h-11"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">No related ProofBox</SelectItem>{boxes.map((box) => <SelectItem key={box.id} value={box.id}>{box.title}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="reminder-note">Note</Label><Input id="reminder-note" name="note" className="mt-2 h-11" placeholder="Optional details" /></div><Button type="submit" className="w-full" disabled={busy}>Create reminder</Button></form>; }